steps:
  ## Create service account
  ##- name: gcr.io/cloud-builders/kubectl
  ##  args:
  ##    - create
  ##    - serviceaccount
  ##    - --namespace
  ##    - '$_K8S_NAMESPACE'
  ##    - items-api
  ##  env:
  ##    - "CLOUDSDK_COMPUTE_REGION=$_GKE_LOCATION"
  ##    - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
  # Build Image
  - name: 'openjdk:11-jdk'
    env: ["GRADLE_USER_HOME=cache"]
    entrypoint: "bash"
    args: [ "-c", "./gradlew bootBuildImage --imageName=$_IMAGE_NAME:$COMMIT_SHA processKubernetesResources --Pdbpass=password"]
  # Push Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output'
    id: Prepare deploy
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    id: Save configs
    entrypoint: sh
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply deploy
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_LABELS: ''
  _K8S_ANNOTATIONS: gcb-trigger-id=11514a9a-14cd-41ef-98a4-5d358f08a2e9
  _IMAGE_NAME: gcr.io/items-project-1/items-api
  _GKE_LOCATION: europe-west6-a
  _K8S_NAMESPACE: default
  _GKE_CLUSTER: production
  _K8S_YAML_PATH: build/kubernetes/
  _OUTPUT_BUCKET_PATH: items-project-1_cloudbuild/deploy
  _K8S_APP_NAME: items-api


