---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "items-api"
  namespace: "default"
  labels:
    app: "items-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "items-api"
  template:
    metadata:
      labels:
        app: "items-api"
    spec:
      containers:
        - name: "items-api-sha256-1"
          image: "gcr.io/items-project-1/items-api@sha256:eeef740e81c61fb728ca8e6d3dd3ab66efa329759e1be14478d3022f01356892"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "items-api-hpa-homr"
  namespace: "default"
  labels:
    app: "items-api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "items-api"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "items-api-service"
  namespace: "default"
  labels:
    app: "items-api"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: "items-api"
  type: "LoadBalancer"
  loadBalancerIP: ""
